# Configurations
title: Jekyll Gitbook Demo
author: PasseRR
description: Build Jekyll site with the GitBook style.

version: 1.0
gitbook_version: 3.2.3

baseurl: '/jekyll-gitbook-theme'
# 主题cdn地址
cdn-url: 'https://cdn.jsdelivr.net/gh/PasseRR/jekyll-gitbook-theme'
# ico地址
ico-url: 'https://cdn.jsdelivr.net/gh/PasseRR/jekyll-gitbook-theme/gitbook/images/favicon.ico'
collections:
  chapters:
    permalink: /:categories/:name:output_ext
    output: true
rss: RSS

toc:
  enabled: false
  h_min: 1
  h_max: 3

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [ index.md, search.html ]

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:name:output_ext

exclude:
  - _drafts

destination: ./_site
incremental: false
regenerate: true
